default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: ../database.db

test:
  <<: *default
  database: ../database.db

production:
  <<: *default
  database: ../database.db
