default: &default
  adapter: mysql2
  host: localhost
  port: 3306
  username: root
  password: password

development:
  <<: *default
  database: db

test:
  <<: *default
  database: db

production:
  <<: *default
  database: db
