name: Sequelize Postgres Manual

on:
  push:
    paths:
      - 'base/sequelize-postgres-manual/**'
      - 'base/pgsql_runner.sh'
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_publish:
    strategy:
      fail-fast: false
      matrix:
        node_versions: 
          [
            { dockerfile: 'Dockerfile', tag: 'sequelize-postgres-manual' },
            { dockerfile: 'Dockerfile18', tag: 'sequelize-postgres-manual-18' }
          ]

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            ${{ matrix.node_versions.tag }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: ./base
          file: base/sequelize-postgres-manual/${{ matrix.node_versions.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/vija02/schema_importer:buildcache
          cache-to: type=registry,ref=ghcr.io/vija02/schema_importer:buildcache,mode=max
      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: schema_importer